before_script:
  - echo Starting...
  - whoami
  - groups
after_script:
  - echo Done.
stages:
  - setup
  - build
setup:
  stage: setup
  script:
    - cp * [temp build directory] -r
    - cd [temp build directory]
    - npm install
build:
  stage: build
  script:
    - cd [temp build directory]
    - ng build --prod --output-path=[output directory]
